name: Stampede Checker

on:
  schedule:
    - cron: "*/2 * * * *"  # run every 2 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Checker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        run: |
          node stampede-checker.mjs
